version: '3.1'

services:
  database:
    container_name: "mongodb_database"
    image: mongo:latest
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "pbOq7vUL4t4fZ5HZaIGiCAtRZJtxywkp"
      MONGO_INITDB_DATABASE: "vault"
    volumes:
      -  /usr/share/pivault/mongodb:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./scripts/insert_icons.sh:/docker-entrypoint-initdb.d/insert_icons.sh:ro
      - ./install/icons.json:/docker-entrypoint-initdb.d/icons.json:ro


  app:
    container_name: "pi-vault-app"
    image: pi-vault:latest #omarmhamza/pi-vault:arm64v8 #use "omarmhamza/pi-vault:latest" for amd64 cpu arch
    ports:
      - "80:5000"
    restart: always
    environment:
      FLASK_ENV: "production"
      MONGO_URI: "mongodb://user:Pl6VuTfrqY@database:27017/vault"
      SECRET_KEY: "qCGX2QaaS3wMTMJ0eRCsM13v9Nc2mlZ1"
    depends_on:
      - database

volumes:
  mongodb_data_container: